"""rename develoeprs to employees

Revision ID: 9d48ba0b7531
Revises: 9b0d36d08f1d
Create Date: 2026-02-10 04:21:42.096027

"""

from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9d48ba0b7531"
down_revision: Union[str, Sequence[str], None] = "9b0d36d08f1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("developers", "employees")
    op.create_table(
        "employee_projects",
        sa.Column("employee_name", sa.String(), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_name"], ["employees.name"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_name"], ["projects.name"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("employee_name", "project_name"),
    )
    op.add_column(
        "employees",
        sa.Column(
            "voice_print", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True
        ),
    )
    op.add_column("meeting_chunks", sa.Column("raw_text", sa.Text(), nullable=False))
    op.add_column(
        "meeting_chunks", sa.Column("summary_text", sa.Text(), nullable=False)
    )
    op.add_column(
        "meeting_chunks", sa.Column("start_time_sec", sa.Float(), nullable=True)
    )
    op.add_column(
        "meeting_chunks", sa.Column("end_time_sec", sa.Float(), nullable=True)
    )
    op.add_column(
        "meeting_chunks",
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
        ),
    )
    op.drop_column("meeting_chunks", "text_content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("employees", "developers")
    op.add_column(
        "meeting_chunks",
        sa.Column("text_content", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_column("meeting_chunks", "meta")
    op.drop_column("meeting_chunks", "end_time_sec")
    op.drop_column("meeting_chunks", "start_time_sec")
    op.drop_column("meeting_chunks", "summary_text")
    op.drop_column("meeting_chunks", "raw_text")
    op.drop_column("developers", "voice_print")
    op.drop_table("employee_projects")
    # ### end Alembic commands ###
