"""nullable changes

Revision ID: b75ad330f6f0
Revises: f1ec11f6e91e
Create Date: 2026-01-14 22:41:10.517475

"""

from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b75ad330f6f0"
down_revision: Union[str, Sequence[str], None] = "f1ec11f6e91e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("developers", sa.Column("gender", sa.String(), nullable=False))
    op.alter_column(
        "developers", "role", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "developers",
        "skills",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.alter_column(
        "meeting_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.VECTOR(dim=1536),
        nullable=False,
    )
    op.alter_column(
        "notes",
        "embedding",
        existing_type=pgvector.sqlalchemy.VECTOR(dim=1536),
        nullable=False,
    )
    op.alter_column(
        "projects", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("tasks", "source_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("source_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "projects", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "notes",
        "embedding",
        existing_type=pgvector.sqlalchemy.VECTOR(dim=1536),
        nullable=True,
    )
    op.alter_column(
        "meeting_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.VECTOR(dim=1536),
        nullable=True,
    )
    op.alter_column(
        "developers",
        "skills",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    op.alter_column(
        "developers", "role", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_column("developers", "gender")
    # ### end Alembic commands ###
