"""create initial tables

Revision ID: f1ec11f6e91e
Revises:
Create Date: 2026-01-14 21:12:13.307818

"""

from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1ec11f6e91e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "developers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("skills", sa.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "category_maps",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_name"],
            ["projects.name"],
        ),
        sa.PrimaryKeyConstraint("name", "project_name"),
    )
    op.create_table(
        "meetings",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_name"],
            ["projects.name"],
        ),
        sa.PrimaryKeyConstraint("meeting_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["developers.name"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.name"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "meeting_chunks",
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.VECTOR(dim=1536), nullable=True),
        sa.Column("speaker_names", sa.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.meeting_id"],
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_table(
        "notes",
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=False),
        sa.Column("project_name", sa.String(), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("note_text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.VECTOR(dim=1536), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_name", "project_name"],
            ["category_maps.name", "category_maps.project_name"],
        ),
        sa.PrimaryKeyConstraint("note_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notes")
    op.drop_table("meeting_chunks")
    op.drop_table("tasks")
    op.drop_table("meetings")
    op.drop_table("category_maps")
    op.drop_table("projects")
    op.drop_table("developers")
    # ### end Alembic commands ###
