"""identity for server

Revision ID: 00d4ef66c199
Revises: ec4979294a52
Create Date: 2026-02-21 23:00:01.578638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00d4ef66c199"
down_revision: Union[str, Sequence[str], None] = "ec4979294a52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_projects",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
    )
    op.create_unique_constraint(
        "uq_name_project_company",
        "employee_projects",
        ["employee_name", "project_name", "company_id"],
    )
    # ### end Alembic commands ###
    op.execute(
        "ALTER TABLE employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )

    op.execute(
        "ALTER TABLE category_maps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_name_project_company", "employee_projects", type_="unique")
    op.drop_column("employee_projects", "id")
    # ### end Alembic commands ###

    op.execute("ALTER TABLE employees ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE category_maps ALTER COLUMN id DROP IDENTITY IF EXISTS")
