"""added features to meeting

Revision ID: 7ed1eb17c3ae
Revises: 9d48ba0b7531
Create Date: 2026-02-14 22:19:35.598116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed1eb17c3ae'
down_revision: Union[str, Sequence[str], None] = '9d48ba0b7531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'employees', ['name'])
    op.add_column('meetings', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('tags', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'projects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'tags')
    op.drop_column('projects', 'id')
    op.drop_column('meetings', 'language')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'id')
    # ### end Alembic commands ###
