"""embedding size for voice

Revision ID: 81c1c9955489
Revises: bf2f61e75eaf
Create Date: 2026-04-09 13:32:54.208733

"""

from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81c1c9955489"
down_revision: Union[str, Sequence[str], None] = "bf2f61e75eaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE employees SET voice_print = NULL")
    op.alter_column(
        "employees",
        "voice_print",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "voice_print",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
