"""fix autoincrementation

Revision ID: 8d7f4ceaa5d3
Revises: 094ee6d4b5fc
Create Date: 2026-02-21 04:58:02.097974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7f4ceaa5d3'
down_revision: Union[str, Sequence[str], None] = '094ee6d4b5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'companies', ['name'])
    op.create_unique_constraint(None, 'companies', ['domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    # ### end Alembic commands ###
