"""change in task column names

Revision ID: 94ec82b6f234
Revises: 67f51a516804
Create Date: 2026-01-17 05:23:15.399250

"""
from typing import Sequence, Union
import pgvector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ec82b6f234'
down_revision: Union[str, Sequence[str], None] = '67f51a516804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_name', sa.String(length=255), nullable=False))
    op.add_column('tasks', sa.Column('assignee_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('tasks_owner_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_project_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'developers', ['assignee_name'], ['name'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_name'], ['name'], ondelete='CASCADE')
    op.drop_column('tasks', 'owner_id')
    op.drop_column('tasks', 'source_id')
    op.drop_column('tasks', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('owner_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_project_id_fkey'), 'tasks', 'projects', ['project_id'], ['name'], ondelete='CASCADE')
    op.create_foreign_key(op.f('tasks_owner_id_fkey'), 'tasks', 'developers', ['owner_id'], ['name'], ondelete='SET NULL')
    op.drop_column('tasks', 'assignee_name')
    op.drop_column('tasks', 'project_name')
    # ### end Alembic commands ###
