"""added metadata column

Revision ID: 9b0d36d08f1d
Revises: 0f6409731a29
Create Date: 2026-01-24 23:44:59.614546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b0d36d08f1d'
down_revision: Union[str, Sequence[str], None] = '67f51a516804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.add_column('notes', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'meta')
    op.drop_column('meetings', 'meta')
    # ### end Alembic commands ###
