"""convert_id_to_identity

Revision ID: bf2f61e75eaf
Revises: 752834e468ae
Create Date: 2026-04-07 01:46:58.986272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf2f61e75eaf"
down_revision: Union[str, Sequence[str], None] = "752834e468ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "ALTER TABLE projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )

    op.execute(
        "SELECT setval(pg_get_serial_sequence('projects', 'id'), coalesce(max(id), 1)) FROM projects"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE projects ALTER COLUMN id DROP IDENTITY IF EXISTS")
