"""add duration col

Revision ID: d410415e0b35
Revises: ec1667a88cbb
Create Date: 2026-02-16 05:19:02.954865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd410415e0b35'
down_revision: Union[str, Sequence[str], None] = 'ec1667a88cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('duration_sec', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'duration_sec')
    # ### end Alembic commands ###
