"""empty message

Revision ID: ec4979294a52
Revises: 8d7f4ceaa5d3
Create Date: 2026-02-21 05:21:48.358725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4979294a52'
down_revision: Union[str, Sequence[str], None] = '8d7f4ceaa5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_maps', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint('uq_category_name_project_company', 'category_maps', ['name', 'project_name', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_name_project_company', 'category_maps', type_='unique')
    op.drop_column('category_maps', 'id')
    # ### end Alembic commands ###
