"""added companies table

Revision ID: f470e0623680
Revises: 06aee029bf29
Create Date: 2026-02-18 23:16:15.204924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f470e0623680'
down_revision: Union[str, Sequence[str], None] = '06aee029bf29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category_maps', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'category_maps', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('employee_projects', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employee_projects', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('employees', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('meetings', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meetings', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('notes', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notes', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'company_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'company_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'company_id')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'company_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'company_id')
    op.drop_constraint(None, 'employee_projects', type_='foreignkey')
    op.drop_column('employee_projects', 'company_id')
    op.drop_constraint(None, 'category_maps', type_='foreignkey')
    op.drop_column('category_maps', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
