volumes:
  postgres_data:
    name: postgres_data

services:
  postgres:
    image: pgvector/pgvector:pg18
    env_file:  
      - ./postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    command: >
      postgres
      -c max_connections=1024
  